# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to Production

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build react project
        run: npm run build --if-present
        env:
          REACT_APP_MAIL_CHIMP_URL: ${{ secrets.MAILCHIMP }}
      - name: zip up the build
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r build.zip build
      - name: Operations
        uses: alinz/ssh-scp-action@master
        with:
          key: ${{ secrets.PROD_SSH_KEY }}
          host: ${{ secrets.PROD_HOST }}
          port: 22
          user: ${{ secrets.USERNAME }}
          # runs this on remove server
          ssh_before: |
            rm -r build.zip
          # then uploads these 2 files
          scp: |
            build.zip ${{ secrets.USERNAME }}@${{ secrets.PROD_HOST }}:~/build.zip

          # then run these commands
          ssh_after: |
            /root/update.sh
